// filepath: c:\Users\Austin\Projects\DepNails\depnails.client\src\aws-exports.js
// This file would typically be auto-generated by the Amplify CLI,
// but you can create it manually.
const awsExports = {
    "aws_project_region": "YOUR_AWS_REGION", // e.g., "us-east-1"
    "aws_cognito_identity_pool_id": "YOUR_IDENTITY_POOL_ID", // Optional: if using Identity Pools
    "aws_cognito_region": "YOUR_AWS_REGION",
    "aws_user_pools_id": "YOUR_USER_POOL_ID", // e.g., "us-east-1_xxxxxxxxx"
    "aws_user_pools_web_client_id": "YOUR_APP_CLIENT_ID", // The App Client ID from Cognito
    "oauth": {},
    "aws_cognito_username_attributes": ["EMAIL"], // Or other attributes you configured
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": ["EMAIL"],
    "aws_cognito_mfa_configuration": "OFF", // Or "ON" / "OPTIONAL"
    "aws_cognito_mfa_types": ["SMS"],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": ["EMAIL"]
};

export default awsExports;